version: '3'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
    command: -p 5432
  backend:
    image: 'kihyeokk/mada-backend'
    build: 'backend'
    depends_on:
      - postgres
    ports:
      - '3001:3001'
  frontend:
    image: 'kihyeokk/mada-frontend'
    build: 'frontend'
    ports:
      - '3000:3000'